import assetsLarge from 'assets/fishes/generic/large';
import assetsSmall from 'assets/fishes/generic/small';
import type { Fish, FishIdGeneric } from 'types/fishes';

// prettier-ignore
const fishes: Omit<Fish<FishIdGeneric>, 'image'>[] = [
  {
    id: 'african-mottled-eel',
    name: 'African Mottled Eel',
    description: 'The African Mottled Eel is a tropical, freshwater eel found in East Africa, Bangladesh, Andaman Islands, Mozambique, Malawi, Sri Lanka, Sumatra, and Indonesia and recently from Madagascar. Though widely distributed, the Mottled Eel is listed as Near Threatened by the IUCN Redlist. Although the Eels are too large for use in aquariums, they are commercial in subsistence fisheries. The Eels spend most of their lives in freshwater at a depth range of 10-32 ft (3-10 m), but migrate to the Indian Ocean to breed. The Eels feed primarily off of crustaceans, mollusks, finfish and worms.',
    reserves: ['sa'],
  },
  {
    id: 'african-sharptooth-catfish',
    name: 'African Sharptooth Catfish',
    description: 'The African Sharptooth Catfish (ASC) is a large, eel-like, air-breathing catfish, found throughout Africa and the Middle East. In the early 1980s, the ASC was introduced into a variety of habitats for aquaculture purposes, and as such, is found in countries such as Brazil, Vietnam, Indonesia, and India. These Catfish typically live in freshwater lakes, rivers, swamps, oxidation ponds or even urban sewage systems. The ASC is one of the very largest Catfish in African waters, with a mouth so large it typically swallows its prey whole. African Catfish sometimes produce loud croaking sounds, not unlike the voice of the crow.',
    reserves: ['sa'],
  },
  {
    id: 'african-tigerfish',
    name: 'African Tigerfish',
    description: 'The African Tigerfish is a predatory freshwater fish distributed throughout much of Africa. This fish is generally a piscivore but it has been observed leaping out of the water and catching barn swallows in flight. They have a large head, fitted with eight sharp teeth per jaw, which they are able to replace simultaneously. Due to its ferocious appearance, people may be tempted to keep the African Tigerfish as a pet. However, this is generally not recommended and should only be attempted by those with advanced skills in keeping freshwater aquariums. In the United States, it is illegal to import this species into Texas, Utah, and Florida.',
    reserves: ['sa'],
  },
  {
    id: 'alpine-bullhead',
    name: 'Alpine Bullhead',
    description: 'The Alpine Bullhead, or Siberian Bullhead, is a species of freshwater fish. It has a wide distribution, and can be found all over Asia and Europe. In northern and central Europe, it tends to prefer coldwater streams and lakes in mountainous regions. The alpine bullhead feeds on insects, crustaceans and small invertebrate prey that it finds on the stream bed. It is generally nocturnal but becomes diurnal in the Arctic during the winter. In spring, when the water temperature rises, a male will prepare a nest under a large stone and several females will lay their eggs in it. The male then guards the nest for the month or so until the eggs hatch.',
    reserves: ['no'],
  },
  {
    id: 'andalusian-barbel',
    name: 'Andalusian Barbel',
    description: 'The Andalusian Barbel is a ray-finned freshwater fish. The Andalusian Barbel is regularly found in the southern Iberian Peninsula, native to both Portugal and Spain. It inhabits the middle and lower parts of rivers, and will typically utilize any applicable location aside from small cool mountain streams. They spawn at the beginning of summer, between May and June. The males reach sexual maturity at 2-4 years of age and around 3.1 in (8 cm), whereas females reach maturity at 6-7 years and at 4.3-6.3 in (11-16 cm) in length. Despite a fairly small size for a Barbel, it has a long life, living up to 18 years.',
    reserves: ['es'],
  },
  {
    id: 'arctic-char',
    name: 'Arctic Char',
    description: "The Arctic Char is a cold-water fish, native to alpine lakes and arctic coastal waters. The English name is thought to derive from the Old Irish ceara/cera for 'blood red', referring to its pink-red belly. This would also connect with its Welsh name torgoch, 'red belly'. No other freshwater fish is found as far north as the Artic Char. The Arctic Char is closely related to both salmon and lake trout, and has many characteristics of both. The fish is highly variable in color, depending on the time of year and the environmental conditions of the lake where it lives. Individual fish can weigh 20 lb (9kg). Generally, whole market-sized fish are around 2-5 lb (1-2 kg).",
    reserves: ['no'],
  },
  {
    id: 'asp',
    name: 'Asp',
    description: 'The Asp is a European freshwater fish of the Carp family, inhabiting the estuaries of the Black, Caspian and Baltic seas. Asp have blue-gray bodies with a white belly. Asp can life up to 15 years, which means the could drink alcohol off-premises in the Central African Republic or work up to 35 hours per week in Scotland. They can grow to an average length of around 3 ft (80 cm) and weigh 4-5 lb (1.8-2.3 kg). Asp feed on insects, worms, crustaceans, and small fish.',
    reserves: ['no'],
  },
  {
    id: 'atlantic-salmon',
    name: 'Atlantic Salmon',
    description: 'Atlantic Salmon is one of the largest species of Salmon and is found primarily in and around the northern Atlantic Ocean. Their average weight ranges from 11-33 lb (5-15 kg). Fully grown Atlantic Salmon feed primarily on other fish.',
    reserves: ['no'],
  },
  {
    id: 'black-crappie',
    name: 'Black Crappie',
    description: 'The Black Crappie is a North American freshwater fish, one of the two types of crappies, along with the White Crappie. Both crappies are very similar in size, shape, and habit, except the Black Crappie is much darker, and is thought to be unlucky if it crosses your path. Crappies are typically about 4-8 in (10-20 cm) long. The maximum length reported for a Black Crappie is 19.3 in (49 cm) and the maximum published weight is under 6 lb (2.72 kg). Crappies are prolific breeders and overpopulate almost any environment they find themselves in. Female crappies produce an average of 40,000 spherical eggs, which are watched over by the male until hatched. Newly hatched fish larvae are about 0.091 in (2.32 mm) long and appear translucent. The oldest recorded age of a specimen is fifteen years, although seven years is a more typical lifespan for the species.',
    reserves: ['us'],
  },
  {
    id: 'blue-kurper',
    name: 'Blue Kurper',
    description: "The Blue Kurper, or Mozambique Tilapia, a freshwater bream, is one of South Africa's most common inland fish species. The Blue Kurper can grow to be more than 7 lb (3 kg) in South African waters, with the South African record for this fish weighing almost 9 lb (4 kg). Many records for this fish have been caught at Loskop Dam, which is widely regarded as one of the best places in South Africa for trophy size Blue Kurper.",
    reserves: ['sa'],
  },
  {
    id: 'bluegill',
    name: 'Bluegill',
    description:
      "The Bluegill is a species of freshwater fish native to North America and lives in streams, rivers, lakes, and ponds. Bluegills can grow up to 12 in (30 cm) long and about 4.5 lb (2 kg). Fishermen are able to use polarized sunglasses to see through water and find bluegills' spawning beds. Bluegill have a rather bold character; many have no fear of humans, eating food dropped into the water, and a population in Canada's Lake Scugog will even allow themselves to be stroked by human observers. Bluegill are omnivores and will eat anything they can fit in their mouth. They mostly feed on small aquatic insects and fish. If food is scarce, Bluegill will also feed on aquatic vegetation and algae, and if scarce enough, will even feed on their own eggs or offspring. To capture prey, bluegills use a suction system in which they accelerate water into their mouth. Prey comes in with this water. Only a limited amount of water is able to be suctioned, so the fish must get within 0.7 in (1.8 cm) of the prey.",
    reserves: ['us'],
  },
  {
    id: 'bream',
    name: 'Bream',
    description: 'The Common Bream is a freshwater gamefish of the Carp family, inhabiting lakes, ponds and rivers all over Europe. Common Breams have flat, high-backed bodies that are silvery gray or bronze in color. Common Bream grow to be 12-22 in (30-55 cm) and weigh around 2-6 lb (1-3 kg). Bream primarily feed on larvae, worms, insects and plankton.',
    reserves: ['no'],
  },
  {
    id: 'brook-trout',
    name: 'Brook Trout',
    description: 'The Brook Trout is a species of freshwater fish, native to Eastern North America in the United States and Canada. The Brook Trout is the state fish of nine U.S. states: Michigan, New Hampshire, New Jersey, New York, North Carolina, Pennsylvania, Vermont, Virginia, and West Virginia, and the Provincial Fish of Nova Scotia in Canada. Typical lengths of the Brook Trout vary from 5.6-9.8 in (25-65 cm), and weights from 0.66 to 6.61 lb (0.3 to 3 kg). The maximum recorded length is 34 in (86 cm) and maximum weight 15 lb (6.6 kg).',
    reserves: ['us'],
  },
  {
    id: 'brown-trout-no',
    name: 'Brown Trout',
    description: 'Brown Trout are a lake and stream species of the Salmon family that migrates from lakes into rivers to spawn and thrive in warmer waters. This prized gamefish is olive-brown in color with tan yellow sides and brown spots. It is a medium-sized fish, growing to be 44 lb (20 kg) or more in weight and and 39 in (1 m) in length. Brown Trout feed predominantly on small fish.',
    reserves: ['no'],
  },
  {
    id: 'brown-trout-es',
    name: 'Brown Trout',
    description: 'Brown Trout are a lake and stream species of the Salmon family that migrates from lakes into rivers to spawn and thrive in warmer waters. This prized gamefish is olive-brown in color with tan yellow sides and brown spots. It is a medium-sized fish, growing to be 44 lb (20 kg) or more in weight and and 39 in (1 m) in length. Brown Trout feed predominantly on small fish.',
    reserves: ['es'],
  },
  {
    id: 'bullhead-catfish',
    name: 'Bullhead Catfish',
    description: "The Brown Bullhead is a species of Catfish that lives in slow-moving, muddy waters with soft bottoms and is widely known as the 'mud cat' or 'mud pout'. The Brown Bullhead is an important clan symbol of the Ojibwe people, wherein it is one of six beings that came out of the sea to form the original clans. An average Brown Bullhead weighs around 1-2 lb (0-1 kg), although can weigh all the way up to 8 lb (3 kg) in extreme cases. These fish are nocturnal feeders and will eat almost anything.",
    reserves: ['no'],
  },
  {
    id: 'burbot',
    name: 'Burbot',
    description: 'The Burbot is the only freshwater cod, and can be found in large rivers and lakes. In 1590s England, it was said that burbot were so common that they were used to feed hogs, however in present day have been utterly eradicated from the area. They have elongated serpent-like bodies and flattened heads, with an average length of 16 in (40 cm), and a weight ranging from 2-17 lb (1-8 kg). Burbot are keen hunters, active primarily during twilight and prey primarily on other fish.',
    reserves: ['us', 'no'],
  },
  {
    id: 'canary-kurper',
    name: 'Canary Kurper',
    description: 'The Canary Kurper is a species that bass will eat not only because of hunger but also out of pure aggression. It is endemic to the Limpopo River system and tributaries in Gauteng, the North West and Zimbabwe. It is regarded mostly as a pest fish. They are brown and green in color, with males having a bright yellow colored chest. They are typically 6-8 in (15-20 cm) in length and 0.7 lb (0.3kg) in weight.',
    reserves: ['sa'],
  },
  {
    id: 'channel-catfish',
    name: 'Channel Catfish',
    description: "The Channel Catfish is North America's most numerous catfish species. It is the official fish of Kansas, Missouri, Iowa, Nebraska, and Tennessee. Channel catfish possess very keen senses of smell and taste. At the pits of their nostrils are very sensitive odor-sensing organs, which can detect several amino acids at about one part per 100 million in water. In addition, the channel catfish has taste buds distributed over the surface of its entire body. This combination of exceptional senses of taste and smell allows the channel catfish to find food in dark, stained, or muddy water with relative ease. Channel Catfish are omnivores and can be seen to eat snails, clams, crustaceans, snakes, frogs, small fish, insects, aquatic plants, algae, seeds, grains, nuts, and even small birds and mammals occasionally.",
    reserves: ['us'],
  },
  {
    id: 'chub',
    name: 'Chub',
    description: 'Chub is a species of freshwater Carp that is widespread throughout Europe. As a rule, Chub can be found in slow moving rivers and waterways with low current. Chub usually grow to a length of up to 2 ft (60 cm) and weigh about 3 lb (2 kg). Chub are big eaters consuming mostly insects, plants and other fish.',
    reserves: ['no'],
  },
  {
    id: 'comizo-barbel',
    name: 'Comizo Barbel',
    description: 'The Comizo Barbel (Iberian barbel) is a ray-finned freshwater fish. The Comizo can grow up to 20 in (50 cm) long and can achieve the greatest weight of all the Spanish barbel, reaching 20 kg (44 lb) or more. The Comizo Barbel is a fish that is constantly moving and therefore difficult to pin down. Comizo move in shoals that are grouped according to size, with the very largest of Comizos generally moving in groups of 2 or 3. The Comizo is an omnivorous fish, however has a predilection for natural food such as crabs, small fish, shrimp and worms. More are captured in winter because of a seasonal decrease in their natural food sources.',
    reserves: ['es'],
  },
  {
    id: 'common-carp-es',
    name: 'Common Carp',
    description: 'The Common Carp is a widespread freshwater fish in the lakes and large rivers of Europe and Asia. Native populations are considered vulnerable to extinction, but the species has also been domesticated, and is often considered a destructive invasive species. The original common carp was found in the Danube River around 2000 years ago, possessing a torpedo-shaped body and a golden-yellow color. ed in bespoke ponds built by the Romans. As aquaculture became profitable, efforts were made to farm the animals. In Europe, domestication of carp as food was spread by monks between the 13-16th centuries. Common carp can grow to very large size in the right conditions. Domesticated carp can grow to a maximum length of 47 in (120 cm), a maximum weight of over 88 lb (40 kg), and an oldest recorded age of 38 years. The average size of the common carp is around 16-31 in (40-80 cm) and 4-30 lb (2-14 kg).',
    reserves: ['es'],
  },
  {
    id: 'common-carp-sa',
    name: 'Common Carp',
    description: 'The Common Carp is a widespread freshwater fish in the lakes and large rivers of Europe and Asia. Native populations are considered vulnerable to extinction, but the species has also been domesticated, and is often considered a destructive invasive species. The original common carp was found in the Danube River around 2000 years ago, possessing a torpedo-shaped body and a golden-yellow color. ed in bespoke ponds built by the Romans. As aquaculture became profitable, efforts were made to farm the animals. In Europe, domestication of carp as food was spread by monks between the 13-16th centuries. Common carp can grow to very large size in the right conditions. Domesticated carp can grow to a maximum length of 47 in (120 cm), a maximum weight of over 88 lb (40 kg), and an oldest recorded age of 38 years. The average size of the common carp is around 16-31 in (40-80 cm) and 4-30 lb (2-14 kg).',
    reserves: ['sa'],
  },
  {
    id: 'common-dace',
    name: 'Common Dace',
    description: 'The Common Dace is a species of freshwater and brackish water fish native to Europe, and a quarry species for coarse anglers. The Common Dace has been widely introduced to areas of Europe where it did not previously occur, such as Ireland in the early 1900s. The Dace was taken to Ireland as a bait fish to catch larger fish such as pike, however has since benefited from parasite release; wherein it has lost its normal set of parasites, and as such has a competitive advantage over native species. The Common Dace is found in rivers and streams, sometime occurring in lakes or in the brackish water at the mouths of rivers.',
    reserves: ['no'],
  },
  {
    id: 'crucian-carp',
    name: 'Crucian Carp',
    description: 'The Crucian Carp is a medium-sized Carp, which is regularly found in northern European regions. Its habitat includes lakes, ponds, and slow-moving rivers. It has been established that the fish is native to England and not introduced. There are reports of hybridization between the Crucian Carp and Goldfish, which has been verified by production of viable hybrids in laboratory conditions. Even though the hybrids cannot reproduce, they are much more adept at finding food and evading predators than their parents, which has been proposed to constitute a possible threat to the native population.',
    reserves: ['es'],
  },
  {
    id: 'cutthroat-trout',
    name: 'Cutthroat Trout',
    description: 'The Cutthroat Trout is a member of the Salmon family native to cold-water tributaries in North America. Cutthroat trout are popular gamefish, especially among fly fishers. The common name cutthroat refers to the distinctive red coloration along the underside of the jaw. At maturity, different populations and subspecies of cutthroat trout can range from 6-40 in (15-102 cm) in length, depending on habitat and food availability.',
    reserves: ['us'],
  },
  {
    id: 'european-bullhead',
    name: 'European Bullhead',
    description: "The European Bullhead is a freshwater fish that is distributed all over Europe, except for the southern peninsula and northern Scandinavia. It is found mainly in rivers. The European Bullhead is also known as the miller's thumb, freshwater sculpin, common bullhead, and cob. Food items eaten by the European Bullhead include benthic insects, crustaceans and other invertebrates. It breeds in the spring, during which the male digs a shallow hole in which batches of eggs are deposited by several females. He then guards the nest for around a month so that the eggs can hatch.",
    reserves: ['no'],
  },
  {
    id: 'european-eel',
    name: 'European Eel',
    description: "The European Eel is a species of eel, a snake-like fish. They are normally 2-3 ft (60-90 cm) long and rarely reach more than 3 ft (1 m). While their lifespan in the wild has not been determined, captives have lived for over 80 years. A specimen known as 'the Brantevik Eel' lived for 155 years in the well of a family home in Brantevik, a fishing village in southern Sweden. Much of the European Eel's life history was a mystery for centuries, as fishermen never caught anything they could identify as a young eel. Unlike many other migrating fish, eels begin their life cycle in the ocean and spend most of their lives in fresh inland water, returning to the ocean to spawn and die.",
    reserves: ['es'],
  },
  {
    id: 'european-perch',
    name: 'European Perch',
    description: 'European Perch is a predatory fish species of the Percidae family, found in freshwater basins and slow-moving rivers, deep lakes and ponds. Perch are distinguished by green bodies with dark vertical bars and red fins. Adult Perch also have a hump between the head and dorsal fin. European Perch usually weigh from 0.5 to 1 kg (1.1 to 2.2 lb), with unique specimen sometimes reaching a weight of up to 2 kg (4 lb). Fully grown Perch feed mostly on invertebrates and other fish.',
    reserves: ['no'],
  },
  {
    id: 'freshwater-drum',
    name: 'Freshwater Drum',
    description: 'The Freshwater Drum is a fish regularly occurring in North and Central America. Its scientific name comes from the Greek for \'single back\', and the Latin for \'grunting\'. This name is derived from the grunting noise that mature males make. This noise comes from a special set of muscles within their body cavity that vibrate against their swim bladder. The purpose of the grunting is unknown, but as it is only present in mature males during the spawning season, it is assumed to have something to do with spawning. The Freshwater Drum prefers clear water, but it is tolerant of turbid and murky water.',
    reserves: ['us'],
  },
  {
    id: 'golden-trout',
    name: 'Golden Trout',
    description: 'The Golden Trout, also known as the Californian Golden Trout, is a species of trout native to California. The Wyoming Game & Fish Department state record Golden Trout measured 28 in (71 cm) and weighed 11.3 lb (5.1 kg), caught in Cook Lake, Wyoming in 1948. In their native habitat, adults range from 6-12 in (15-30 cm) long. Fish over 12 in (30 cm) are considered large. Golden Trout that have been transplanted to lakes have been recorded up to 11 lb (5 kg).',
    reserves: ['us'],
  },
  {
    id: 'grayling',
    name: 'Grayling',
    description: 'European Grayling are a species of freshwater Salmon that are widespread throughout all of Europe, inhabiting large fast flowing rivers with clean cold water. They have elongated bodies with oblong heads, which are covered in small greenish gray scales. Grayling usually grow up to 21 in (50 cm) in length with an average weight of 1-2 lb (0-1 kg). These predatory fish feed mostly on crustaceans, molluscs, small fish and insects.',
    reserves: ['no'],
  },
  {
    id: 'grass-carp',
    name: 'Grass Carp',
    description: 'The Grass Carp is a species of large herbivorous freshwater fish native to the Pacific Far East, with a native range stretching from northern Vietnam to the Sino-Russian border. Grass Carp are resident fish of large turbid rivers and associated floodplain lakes/wetlands with a wide range of temperature tolerance, and spawn at temperatures of 68-86 °F (20-30 °C). The Grass Carp has been cultivated as a food fish in China for centuries, and is known as one of the Four Domestic Fish, but was later introduced to Europe and the United States for aquatic weed control, becoming the fish species with the largest reported farmed production globally - over five million tonnes per year.',
    reserves: ['sa'],
  },
  {
    id: 'green-sunfish',
    name: 'Green Sunfish',
    description: 'The Green Sunfish is a species of freshwater fish, common among anglers and hobbyists as a panfish and aquarium fish. They are usually caught by accident, however can be caught fairly easily if desired. The Green Sunfish is considered an invasive species by the states of Arizona, California, Florida, Georgia and New Jersey. The typical length ranges from about 3-7 in and usually weighs less than 1 lb. The Green Sunfish has reached a maximum recorded length of about 12 in (30 cm), with a maximum recorded weight of 2.2 lb (960 g).',
    reserves: ['us'],
  },
  {
    id: 'ide',
    name: 'Ide',
    description: 'Ide is a freshwater fish of the Carp family that prefers the clear waters of large rivers and lakes. Ide is a popular ornamental fish and can be recognized by plump bodies and dark backs. They grow to a weight of 1-3 lb (0-2 kg), These omnivorous fish eat aquatic plants, insects, worms and larvae.',
    reserves: ['no'],
  },
  {
    id: 'kokanee-salmon',
    name: 'Kokanee Salmon',
    description: 'The Kokanee Salmon is the non-anadromous form of the sockeye salmon. While size range of Kokanee is often lake-specific and depends on many factors, in typical populations the Kokanee grows to an average size of 9-12 in (23-30 cm) with an average weight of 1 lb (0.5 kg). Kokanee are very sensitive to water temperatures, and cannot survive in non-optimal temperatures. Because their regular food is so small, the general understanding of angling for Kokanee is to irritate the fish enough so that it strikes your lure out of anger rather than as a predator.',
    reserves: ['us'],
  },
  {
    id: 'lake-trout',
    name: 'Lake Trout',
    description: 'The Lake Trout is a freshwater char living mainly in lakes in northern North America. The Lake Trout is prized both as a game fish and as a food fish. Lake Trout are the largest of the chars; the record weighed almost 102 lb (46 kg) with a length of 50 in (127 cm), and 15-40 lb (7-18 kg) fish are not uncommon. The average length is 24-36 in. The largest caught on a rod and reel according to the IGFA was 72 lb (32 kg), caught in Great Bear Lake in 1995 with a length of 59 in (150 cm).',
    reserves: ['us'],
  },
  {
    id: 'largemouth-bass-es',
    name: 'Largemouth Bass',
    description: "The Largemouth Bass is a freshwater gamefish native to the eastern and central United States, southeastern Canada and northern Mexico. The Largemouth Bass has an average lifespan of 10 to 16 years and can reach a maximum recorded overall length of 29.5 in (74.9 cm) and a maximum unofficial weight of 25.1 lb (11.3 kg). Bernard Germain de Lacépède was the first to describe the Largemouth Bass in 1802, giving it the name Labrus Salmoides. The juvenile Largemouth Bass consumes mostly small bait fish, scuds, water fleas, copepods, small shrimp, and insects. Adults consume smaller fish, shad, worms, snails, crayfish, frogs, snakes, salamanders, bats and even small water birds, mammals, turtle hatchlings, and alligator hatchlings. Prey items can be as large as 50% of the bass's body length or larger. Largemouth bass are a highly sought after angling fish, boasting a high-octane exciting 'fight', with fish often becoming airborne in an effort to throw the hook.",
    reserves: ['es'],
  },
  {
    id: 'largemouth-bass-us',
    name: 'Largemouth Bass',
    description: "The Largemouth Bass is a freshwater gamefish native to the eastern and central United States, southeastern Canada and northern Mexico. The Largemouth Bass has an average lifespan of 10 to 16 years and can reach a maximum recorded overall length of 29.5 in (74.9 cm) and a maximum unofficial weight of 25.1 lb (11.3 kg). Bernard Germain de Lacépède was the first to describe the Largemouth Bass in 1802, giving it the name Labrus Salmoides. The juvenile Largemouth Bass consumes mostly small bait fish, scuds, water fleas, copepods, small shrimp, and insects. Adults consume smaller fish, shad, worms, snails, crayfish, frogs, snakes, salamanders, bats and even small water birds, mammals, turtle hatchlings, and alligator hatchlings. Prey items can be as large as 50% of the bass's body length or larger. Largemouth bass are a highly sought after angling fish, boasting a high-octane exciting 'fight', with fish often becoming airborne in an effort to throw the hook.",
    reserves: ['us'],
  },
  {
    id: 'largemouth-yellowfish',
    name: 'Largemouth Yellowfish',
    description: 'The Largemouth Yellowfish is a ray-finned fish species in the Carp family. They are predators of aquatic invertebrates, with adults feeding almost exclusively on other fish. Spawning occurs in riffles during summer, during which a large female can lay more than 60,000 eggs. They are slow-growing and long-lived, and reach a total length of 12 in (30 cm) after only five years.',
    reserves: ['sa'],
  },
  {
    id: 'mirror-carp-es',
    name: 'Mirror Carp',
    description: "Mirror Carp, regionally known as Israeli carp, are a type of fish commonly found in Europe. Their name originates from the reflective quality of their scales. They can grow in excess of 60 lb (27 kg), with the last few British record fish all being Mirror Carp. A population of Mirror Carp in Madagascar was found to have reverted to full scale 'mirror' cover after being introduced from France in the early twentieth century. The feral Carp still possessed large scales due to their mirror phenotype, but had increased scale coverage approaching that of wild-type Carp.",
    reserves: ['es'],
  },
  {
    id: 'mirror-carp-sa',
    name: 'Mirror Carp',
    description: "Mirror Carp, regionally known as Israeli carp, are a type of fish commonly found in Europe. Their name originates from the reflective quality of their scales. They can grow in excess of 60 lb (27 kg), with the last few British record fish all being Mirror Carp. A population of Mirror Carp in Madagascar was found to have reverted to full scale 'mirror' cover after being introduced from France in the early twentieth century. The feral Carp still possessed large scales due to their mirror phenotype, but had increased scale coverage approaching that of wild-type Carp.",
    reserves: ['sa'],
  },
  {
    id: 'moggel',
    name: 'Moggel',
    description: "The Moggel is a freshwater African Carp. They can withstand temperatures below 50 °F (10 °C) and is usually found in stagnant water, muddy dams and large impoundments. Juveniles of the species prey on invertebrates, whereas adults subsist on detritus and mud. They are valued as an important, nutritious food source and is recommended for use in wastewater aquaculture in combination with other aquatic organisms. Moggel are occasionally caught by anglers using bait or flies whilst targeting other species and is known for its strong fighting ability. They are often regarded as an 'easter egg' fish when caught, as they are nearly impossible to target specifically and catches are usually by chance.",
    reserves: ['sa'],
  },
  {
    id: 'mountain-whitefish',
    name: 'Mountain Whitefish',
    description: 'The Mountain Whitefish is a widely distributed salmonid fish of western North America. It is a fish of mountain streams and lakes, favoring clear cold water and large deep pools of at least 3 ft (91 cm). Mountain whitefish are bottom feeders, stirring up the substrate with pectoral and tail fins to expose insect larvae and other invertebrates, including snails, crayfish, and amphipods. Their main feeding time is in the evening, but they will also take drifting prey during the day. The mountain whitefish frequently feeds in the lower strata of streams, but populations may rise to the surface to prey on hatching insects, including mayflies.',
    reserves: ['us'],
  },
  {
    id: 'northern-pike-es',
    name: 'Northern Pike',
    description: "The Northern Pike is a species of carnivorous fish of the genus Esox. Pike can grow to a relatively large size: the average length is 16-22 in (41-55 cm), with maximum recorded lengths of up to 69 in (175 cm) and published weights of 65 lb (29 kg). The northern pike gets its common name from its resemblance to the pole-weapon. In Finnish epic poetry, a wise demigod creates a magical string instrument from the jawbone of a giant pike. Pike is generally known as a 'sporting' quarry and is very exciting, with aggressive hits and aerial acrobatics. In recent decades, more pike are released back to the water after catching, but they can easily be damaged when handled. Handling those fish with dry hands can easily damage their mucus-covered skin and possibly lead to their deaths from infections. In Finland, catching a pike weighing at least 22 lb (10 kg) is considered the qualification as a master fisherman.",
    reserves: ['es'],
  },
  {
    id: 'northern-pike-no',
    name: 'Northern Pike',
    description: "The Northern Pike is a species of carnivorous fish of the genus Esox. Pike can grow to a relatively large size: the average length is 16-22 in (41-55 cm), with maximum recorded lengths of up to 69 in (175 cm) and published weights of 65 lb (29 kg). The northern pike gets its common name from its resemblance to the pole-weapon. In Finnish epic poetry, a wise demigod creates a magical string instrument from the jawbone of a giant pike. Pike is generally known as a 'sporting' quarry and is very exciting, with aggressive hits and aerial acrobatics. In recent decades, more pike are released back to the water after catching, but they can easily be damaged when handled. Handling those fish with dry hands can easily damage their mucus-covered skin and possibly lead to their deaths from infections. In Finland, catching a pike weighing at least 22 lb (10 kg) is considered the qualification as a master fisherman.",
    reserves: ['no'],
  },
  {
    id: 'northern-pike-us',
    name: 'Northern Pike',
    description: "The Northern Pike is a species of carnivorous fish of the genus Esox. Pike can grow to a relatively large size: the average length is 16-22 in (41-55 cm), with maximum recorded lengths of up to 69 in (175 cm) and published weights of 65 lb (29 kg). The northern pike gets its common name from its resemblance to the pole-weapon. In Finnish epic poetry, a wise demigod creates a magical string instrument from the jawbone of a giant pike. Pike is generally known as a 'sporting' quarry and is very exciting, with aggressive hits and aerial acrobatics. In recent decades, more pike are released back to the water after catching, but they can easily be damaged when handled. Handling those fish with dry hands can easily damage their mucus-covered skin and possibly lead to their deaths from infections. In Finland, catching a pike weighing at least 22 lb (10 kg) is considered the qualification as a master fisherman.",
    reserves: ['us'],
  },
  {
    id: 'ohrid-trout',
    name: 'Ohrid Trout',
    description: 'The Ohrid Trout or the Lake Ohrid Brown Trout is a species of trout originating from Lake Ohrid, North Macedonia/Albania, in its tributaries and outlets. The Ohrid Trout is a specialty in Macedonian and Albanian gastronomy, used for soups and other dishes. It tastes like Brown Trout crossed with Atlantic Salmon. The Ohrid Trout is depicted on the Macedonian 2 denars coin, issued in 1993.',
    reserves: ['us'],
  },
  {
    id: 'pumpkinseed',
    name: 'Pumpkinseed',
    description: 'The Pumpkinseed, also referred to as the Pond Perch, is a small fish with a body shaped like a pumpkin seed. It is typically about 4 in (10 cm) in length, but can grow up to 11 in (28 cm). They typically weigh less than 1 lb (450 g). Pumpkinseeds are very similar to the larger Bluegill, and are often found in the same habitat. Pumpkinseeds are carnivorous and feed on a variety of small prey, including insects, small molluscs and small crawfish, as well as cannibalizing smaller Pumpkinseeds.',
    reserves: ['es'],
  },
  {
    id: 'purple-labeo',
    name: 'Purple Labeo',
    description: "The Purple Labeo is a large bottom-dwelling African Carp. It tends to stay in warm rocky areas of large rivers. It can also be found in fairly strong currents. Purple Labeo range from around 15-20 in (40-50 cm) in length and 3-11 lb (1-5 kg) in weight. They typically feed on algae, tearing them away from boulders and other hard surfaces. A distinctive feature of this fish's behavior is feeding off of hippos, wherein the Labeos pluck algae and peel skin from the animals.",
    reserves: ['sa'],
  },
  {
    id: 'rainbow-trout',
    name: 'Rainbow Trout',
    description:
      'The Rainbow Trout is a trout native to cold-water tributaries of the Pacific Ocean in Asia and North America. Adult freshwater stream Rainbow Trout average between 1-5 lb (0.4-2.2 kg), while lake-dwelling and anadromous forms may reach 20 lb (9 kg). Coloration varies widely based on subspecies, forms and habitat. Adult fish are distinguished by a broad reddish stripe along the lateral line, from gills to the tail, which is most vivid in breeding males. Rainbow Trout are predators with a varied diet and will eat nearly anything they can capture. Rainbow Trout, including juvenile steelhead in fresh water, routinely feed on larval, pupal and adult forms of aquatic insects. They also eat fish eggs and adult forms of terrestrial insects that fall into the water. Rainbow Trout and Steelhead are highly regarded game fish. Rainbow Trout are a popular target for fly fishers, and several angling methods are used. Many anglers consider the Rainbow Trout the hardest-fighting trout species, as this fish is known for leaping when hooked and putting up a powerful struggle. It is considered one of the top five sport fish in North America and the most important game fish west of the Rocky Mountains.',
    reserves: ['us'],
  },
  {
    id: 'redbreast-kurper',
    name: 'Redbreast Kurper',
    description: 'The Redbreast Kurper, or Redbreast Tilapia, is a standard food source for bass in the areas of South Africa that have the climate to produce trophy bass. The Redbreast has been introduced into a number of dams and lakes as a means of weed control because they can consume large amounts of vegetation and algae. They are typically found at 10-13 cm (4-5 in). The Redbreast is unique in that it is the only tilapia species that is not a maternal mouth brooder. Instead, the eggs and subsequent young are guarded on a rock or in a crater by both parents. These craters can be huge, up to 61,024 cubic inches (1 meters cubed), and can be seen all along the shorelines where they breed.',
    reserves: ['sa'],
  },
  {
    id: 'rednose-labeo',
    name: 'Rednose Labeo',
    description: 'The Rednose Labeo is a bottom-dwelling African Carp. They can be found in shallow areas, but mainly inhabit deep waters. They tend to reach about 10 in (27 cm) long at maturity, however have been known to reach over 20 in (49 cm) in length and 8 lb (3.6 kg) in weight. Rednose Labeo feed in schools across muddy and rocky bottoms, consuming algae, worms, small crustaceans, and mollusks.',
    reserves: ['sa'],
  },
  {
    id: 'roach-es',
    name: 'Roach',
    description: 'Common Roach is a species of freshwater Carp found all over Europe. These fish inhabit both freshwater and brackish environments and survive in incredibly cold temperatures, but usually dwell in lakes and slow rivers. Common Roach usually grow to a length of 6-16 in (15-40 cm) and can weigh up to 5 lb (2 kg). They feed primarily on algae, aquatic vegetation, insect larvae, mollusks and other invertebrates.',
    reserves: ['es'],
  },
  {
    id: 'roach-no',
    name: 'Roach',
    description: 'Common Roach is a species of freshwater Carp found all over Europe. These fish inhabit both freshwater and brackish environments and survive in incredibly cold temperatures, but usually dwell in lakes and slow rivers. Common Roach usually grow to a length of 6-16 in (15-40 cm) and can weigh up to 5 lb (2 kg). They feed primarily on algae, aquatic vegetation, insect larvae, mollusks and other invertebrates.',
    reserves: ['no'],
  },
  {
    id: 'rock-bass',
    name: 'Rock Bass',
    description: 'The Rock Bass, also known as the Rock Perch and Red Eye, is a freshwater fish native to North America. They are similar in appearance to the Smallmouth Bass, however are typically significantly smaller. The average Rock Bass is around 6-10 in (15-25 cm) long, and rarely weigh over 1 lb (0.4 kg). Rock Bass can live to be around 12 years old. They prefer clear, rocky, and vegetated stream pools and lake margins.',
    reserves: ['us'],
  },
  {
    id: 'rudd',
    name: 'Rudd',
    description: 'The Common Rudd is a freshwater fish spread around Europe and middle Asia. The Rudd is very similar to the Roach, except with yellow eyes with a big red spot above the pupil. The Rudd grows up to a size of 18-20 in (45-50 cm) with an average of about 10 in (25 cm). Rudd were reported in the United States at least as early as 1925. It is unlawful to possess live Rudd in the state of Tennessee. No person,or corporation can possess, sell, offer for sale, import, bring or release Rudd into the State of Alabama.',
    reserves: ['es'],
  },
  {
    id: 'ruffe',
    name: 'Ruffe',
    description: 'The Ruffe, also known as the Eurasian Ruffe or Pope, is a freshwater fish found in temperate regions of Europe and northern Asia. It has been introduced into the Great Lakes of North America, reportedly with unfortunate results, wherein it has become invasive and reproduces faster than other species. The Ruffe has the capacity to reproduce at an extremely high rate. A Ruffe usually matures in two to three years, but a ruffe that lives in warmer waters has the ability to reproduce in the first year of life. A single female has the potential to lay from 130,000 to 200,000 eggs annually. Ruffe will leave the deep dark water where they prefer and journey to warmer shallow water for spawning.',
    reserves: ['no'],
  },
  {
    id: 'sauger',
    name: 'Sauger',
    description: 'The Sauger is a freshwater fish that resembles its close relative, the walleye. The typical sauger is 11-14 oz (0.3-0.4 kg) in weight. Saugers require warmer summer water temperatures of 68-83 F (20-28 C). Their need for warm water is thought to affect the nothern and western boundaries of their range. Saugers feed on a variety of invertebrates and small fishes depending on the time of year and size of the Sauger. The channel catfish is a classic prey of the Sauger. Saugers are more likely to be found in large rivers with deep pools. They encounter a variety of habitats because of their migratory tendencies.',
    reserves: ['us'],
  },
  {
    id: 'shovelnose-sturgeon',
    name: 'Shovelnose Sturgeon',
    description: 'The Shovelnose Sturgeon is the smallest species of freshwater sturgeon native to North America. Sturgeons are highly regarded for their flesh and their roe, which are used to create premium grades of caviar. In 2010, they were listed as threatened under the U.S. Endangered Species Act due to their resemblance to the endangered Pallid Sturgeon. They can reach up to 39 in (1 m) in length and 11 lb (4.8 kg) in weight.',
    reserves: ['us'],
  },
  {
    id: 'smallmouth-bass-sa',
    name: 'Smallmouth Bass',
    description: 'The Smallmouth Bass is a species of freshwater gamefish sought by anglers throughout the temperate zones of North America. The maximum recorded size is approximately 27 in (68 cm) and 12 lb (5 kg). Males tend to range around 2 lb (0.9 kg) while females can range from 3-6 lb (1-3 kg). They have been seen eating tadpoles, fish, aquatic insects, and crayfish. Smallmouth bass are a highly sought after game fish, frequently fished by anglers using conventional spinning and bait casting, as well as fly fishing. The smallmouth bass is potentially the toughest fighting freshwater fish in North America, and is commonly the targeted species in many fresh water fishing tournaments. In addition to wild populations, the smallmouth bass is stocked in cool rivers and lakes throughout Canada and the United States. In shallow streams, it is a wary fish, though usually not to the extent of most trout. According to many, smallmouth typically put up a better, more exciting fight than any other black bass.',
    reserves: ['sa'],
  },
  {
    id: 'smallmouth-bass-us',
    name: 'Smallmouth Bass',
    description: 'The Smallmouth Bass is a species of freshwater gamefish sought by anglers throughout the temperate zones of North America. The maximum recorded size is approximately 27 in (68 cm) and 12 lb (5 kg). Males tend to range around 2 lb (0.9 kg) while females can range from 3-6 lb (1-3 kg). They have been seen eating tadpoles, fish, aquatic insects, and crayfish. Smallmouth bass are a highly sought after game fish, frequently fished by anglers using conventional spinning and bait casting, as well as fly fishing. The smallmouth bass is potentially the toughest fighting freshwater fish in North America, and is commonly the targeted species in many fresh water fishing tournaments. In addition to wild populations, the smallmouth bass is stocked in cool rivers and lakes throughout Canada and the United States. In shallow streams, it is a wary fish, though usually not to the extent of most trout. According to many, smallmouth typically put up a better, more exciting fight than any other black bass.',
    reserves: ['us'],
  },
  {
    id: 'smallmouth-yellowfish',
    name: 'Smallmouth Yellowfish',
    description: 'The Smallmouth Yellowfish is a species of ray-finned fish, which is an invasive species in rivers of the Eastern Cape, South Africa. They are a hardy and adaptable species that are widespread across their natural distribution range. They have the ability to inhabit smaller streams due to their smaller size. Smallmouth Yellowfish are opportunistic feeders, reaching a mass of around 20 lb (9 kg) and eating a variety of food types, ranging from plant material to aquatic insects, crabs, shrimps and small fish.',
    reserves: ['sa'],
  },
  {
    id: 'spotted-bass',
    name: 'Spotted Bass',
    description: 'The Spotted Bass is a freshwater fish native to North America that has been introduced to South Africa, where it has become established as an invasive species. Spotted Bass can reach up to 25 in (64 cm) in length, and up to 11 lb (5.2 kg) in weight. They can often live to a ripe old age of seven. Spotted Bass typically prefer cool or warm mountain streams with rocky bottoms, and feed on insects, crustaceans, frogs, worms and smaller fish. They are often mistaken for the Largemouth Bass, however, quite predictably, they have a smaller mouth.',
    reserves: ['sa'],
  },
  {
    id: 'tench',
    name: 'Tench',
    description: "The Tench, or Doctor Fish, is a freshwater fish from Western Europe. It inhabits slow-moving freshwater habitats such as lakes or lowland rivers. Tench have a stocky, carp-like shape and can be as long as 28 in (70 cm). The Tench has small scales deeply embedded in a thick skin, making the fish incredibly slippery. Folklore has said that this slime cures any sick fish that rubs against it, bestowing the name 'Doctor Fish'.",
    reserves: ['es'],
  },
  {
    id: 'thicklip-mullet',
    name: 'Thicklip Mullet',
    description: 'The Thicklip Mullet is a coastal fish commonly found in sheltered coasts, estuaries, and around power station or sewer outfalls. It is typically about 13 in (32 cm) long, with 30 in (75 cm) being the maximum recorded length. It feeds mainly on benthic diatoms, epiphytic algae, small invertebrates and detritus. The Thicklip Grey Mullet lays its eggs in winter.',
    reserves: ['es'],
  },
  {
    id: 'thinlip-mullet',
    name: 'Thinlip Mullet',
    description: 'The Thinlip Mullet is a species of fish found in shallow European waters. The Thinlip Mullet has an elongated body that is laterally compressed. Their head is short and flat, with a broad mouth and narrow upper lip. Thinlip Mullets have a maximum length of around 27 in (70 cm), however they are commonly around 14 in (35 cm). The largest specimens in the world weigh over 7 lb (3 kg).',
    reserves: ['es'],
  },
  {
    id: 'tiger-muskie',
    name: 'Tiger Muskie',
    description: "The Tiger Muskellunge, commonly called the Tiger Muskie, is the usually sterile, hybrid offspring of the True Muskellunge and Norther Pike. They are known to be incredibly strong and large fish, growing to over 50 in (130 cm). Like other hybrid species, Tiger Muskie is said to have 'hybrid vigor', meaning they grow faster and stronger than their parent fish. They are an elite catch and a difficult fight. Tiger Muskies have been known to turn to cannibalism if the water temperature gets too low.",
    reserves: ['us'],
  },
  {
    id: 'walleye',
    name: 'Walleye',
    description: 'The Walleye, also known as the Yellow Perch or Yellow Pickerel, is a freshwater fish native to Canada and most of North America. The fish is called Walleye due to its opaque, reflective eyes which allow it to see in dark conditions. Walleyes grow to around 31 in (80 cm) in length, and weigh up to about 20 lb (9 kg). The maximum recorded size for the fish is 42 in (107 cm) in length and 29 lb (13 kg) in weight.',
    reserves: ['us'],
  },
  {
    id: 'wels-catfish',
    name: 'Wels Catfish',
    description: 'The Wels Catfish, also called Sheatfish or just Wels, is a large species of catfish native to wide areas of central, southern, and eastern Europe. It has been introduced to Western Europe as a prized sport fish, and is now found from the United Kingdom to Kazakhstan and China, and south to Greece and Turkey. With a total length possibly exceeding 9.8 ft (3 m) and a maximum weight of over 440 lb (200 kg), the Wels is the largest freshwater fish in Europe and Western Asia, however such lengths are unproven in modern times. Younger Wels Catfish are about 31-51 in (80-130cm) in length, and up to about 33 lb (15 kg) in weight. The Wels Catfish is a long-lived species and can live up to 70 years old.',
    reserves: ['es'],
  },
  {
    id: 'white-crappie',
    name: 'White Crappie',
    description: 'The White Crappie is a freshwater fish found in North America, and is one of the two species of Crappies along with the Black Crappie. They are also known as the goldring, a name derived from the vaguely vertical bars or \'rings\' along their bodies, silver perch, white perch and sac-a-lait. White crappies can be found in large rivers, reservoirs, and lakes, and are more tolerant of turbid waters than Black Crappies, in which they normally outnumber their black brethren. The ship USS Goldring is named after the fish.',
    reserves: ['us'],
  },
  {
    id: 'yellow-perch',
    name: 'Yellow Perch',
    description: "The Yellow Perch is a freshwater fish native to much of North America. The maximum recorded total length is 20 in (50 cm) although they are more commonly around 7.5 in (19 cm) and the maximum published weight is 4.2 lb (2 kg). Yellow Perch is often recognized by its dark vertical stripes and gold or yellow body color. It's name is derived from early Greek for 'perch' and Latin for 'becoming gold.' Yellow perch are a popular sport fish, prized by both recreational anglers and commercial fishermen for their delicious, mild flavor. The voracious feeding habits of yellow perch make them fairly easy to catch when schools are located, and they are frequently caught by recreational anglers targeting other species.",
    reserves: ['us'],
  },
  {
    id: 'zander-es',
    name: 'Zander',
    description: 'Zander is a popular European game species of fish that is closely related to Perch. Zander is considered to be a hybrid of Pike and Perch, although it looks a lot more like a Pike due to its elongated body, with the spiny dorsal fin of a Perch. Zander usually grow to an average weight of 4-9 lb (2-4 kg). Similar to Perch, Zander are carnivorous, and feed mostly on other fish.',
    reserves: ['es'],
  },
  {
    id: 'zander-no',
    name: 'Zander',
    description: 'Zander is a popular European game species of fish that is closely related to Perch. Zander is considered to be a hybrid of Pike and Perch, although it looks a lot more like a Pike due to its elongated body, with the spiny dorsal fin of a Perch. Zander usually grow to an average weight of 4-9 lb (2-4 kg). Similar to Perch, Zander are carnivorous, and feed mostly on other fish.',
    reserves: ['no'],
  },
];

export default fishes.map<Required<Fish<FishIdGeneric>>>(fish => ({
  ...fish,
  image: {
    large: assetsLarge[fish.id],
    small: assetsSmall[fish.id],
  },
  legendary: false,
}));
